name: fengari_lua
description: Dart bindings for fengari-web, a Lua 5.3 interpreter.
version: 1.0.0
homepage: https://github.com/PixelToast/dart-fengari-lua

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  js: ^0.6.0
  quiver: '>=2.0.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.4
